[[redirects]]
  from = "https://dasfilter.co/:path"
  to = "https://dasfilter.shop/:path"
  status = 301
  force = true
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}
